@startuml "inheritance"
abstract class Doctor {
  {abstract} diagnose(): void
}

class Neurologist {
  diagnose(): void()
}

note left of Neurologist: request nervous system labs

class Ophthalmologist {
  diagnose(): void()
}

note right of Ophthalmologist: request visual acuity test

class NeuroOphthalmologist {

}

note bottom of NeuroOphthalmologist: doesn't override diagnose()\n\n which diagnose() will it inherit?

Doctor <|-- Neurologist
Doctor <|-- Ophthalmologist
Neurologist <|-- NeuroOphthalmologist
Ophthalmologist <|-- NeuroOphthalmologist
@enduml