@startuml "inheritance"
class Animal {
  + scientificName: String
  + sound: String {readOnly}
  - _oxygenLevel: int

  + breathe(): void
  + eat(food: String): void
  + makeSound(): void
  + reproduce(mate: Animal): Animal[]
}

note right of Animal: I am a note: {readOnly} means final\n 
note bottom of Animal: [] means array / list

class Dog {
  + missesOwner: bool

  + wagTail(): void
}

class Cat {
  + lives: int

  + climb(): void
}

class Bird {
  + fly(): void
}

Animal <|-- Dog
Animal <|-- Cat
Animal <|-- Bird
@enduml