@startuml "inheritance"
interface Whistler {
  + {abstract} whistle(): void
}

together {
  class Animal {}
  class Wolf {
    + whistle(): void
  }
  class Cricket {
    + whistle(): void
  }
  class Snake {
  }
}

together {
  class Kitchenware
  class FryingPan {}
  class Kettle {
    + whistle(): void
  }
}

together {
  class Firework {}
  class WhistleBomb {
    + whistle(): void
  }
  class Skyrocket {}
}

Animal <|-- Wolf
Animal <|-- Cricket
Animal <|-- Snake

Kitchenware <|-- FryingPan
Kitchenware <|-- Kettle

Whistler <|.. Wolf
Whistler <|.. Cricket
Whistler <|.. Kettle
Whistler <|.. WhistleBomb

Firework <|-- WhistleBomb
Firework <|-- Skyrocket
@enduml